repos:
  - repo: local
    hooks:
      - id: npm-lint-fix
        name: npm lint:fix
        entry: npm run lint:fix
        language: node
        types: [file]
        files: \.(js|ts|svelte)$
        exclude: ^(node_modules|build|\.svelte-kit)/
